platform :ios, '8.0'
target ‘MosquitoNote’ do
    pod 'AFNetworking'
    pod 'MJRefresh'
    pod 'SDWebImage'
    pod 'Masonry'
    pod 'SVProgressHUD'
    pod 'IQKeyboardManager'
    pod 'MJExtension'
    pod 'MJRefresh'
    pod 'BRPickerView'
    pod 'Masonry'
    pod 'YYCategories'
    
    target 'MosquitoNoteTests' do
        inherit! :search_paths
    end
    
    target 'MosquitoNoteUITests' do
        inherit! :search_paths
    end

end


